image: node:latest

stages:
  - production
production:
#  type: deploy
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - gem install faraday -v 1.8.0
    - dpl --provider=heroku --app=animal-rights-advocates-bot --api-key=$HEROKU_API_KEY
  only:
    - main
